export default {
  questions: [
    {
      _id: '6405c169052cdb001d6e98da',
      type: 'GRAPHING',
      published: true,
      structure: {
        settings: {
          graphData: {
            type: 'Quadratic',
            maxPoints: 2,
            sizer: 1,
          },
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [
          '6405c129ff0f5ff3b5f6e082',
        ],
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405c169052cdb001d6e98e6',
          media: [],
          text: '',
        },
        kind: 'GRAPHING',
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0e1ff0f5ff3b5f6e035',
            text: 'Russia',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0d7ff0f5ff3b5f6e033',
            text: 'Ukraine',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0caff0f5ff3b5f6e031',
            text: 'Finland',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0a4ff0f5ff3b5f6e02f',
            text: 'Italy',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c08fff0f5ff3b5f6e02d',
            text: 'Turkey',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c088ff0f5ff3b5f6e02b',
            text: 'United Kingdom',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c082ff0f5ff3b5f6e029',
            text: 'Norway',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e019',
            text: 'France',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e01a',
            text: 'Germany',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e01c',
            text: 'Spain',
          },
        ],
        graphs: [
          {
            data: {
              points: {
                vertex: {
                  loc: {
                    x: -5,
                    y: -5,
                  },
                },
                pathPoint: {
                  loc: {
                    x: -2,
                    y: 4,
                  },
                },
              },
            },
            type: 'Quadratic',
            plotId: '6405c129ff0f5ff3b5f6e082',
            equation: 'y = x^2 + 10x + 20',
          },
        ],
        query: {
          math: {
            latex: [
              'f\\left(x\\right)\\ =\\ x^2\\ +\\ 10x\\ +\\ 20',
            ],
            template: '<p>Plot the graph for</p><p> </p><p>{$0}></p>',
          },
          type: 'text',
          hasMath: true,
          answerTime: -1,
          _id: '6405c169052cdb001d6e98db',
          media: [],
          text: '<p>Plot the graph for</p><p> </p><p><katex latex="f\\left(x\\right)\\ =\\ x^2\\ +\\ 10x\\ +\\ 20"></katex></p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T10:33:13.403Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 180000,
    },
    {
      _id: '6405c775ace5b5001d9f73aa',
      type: 'DND_IMAGE',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405c834f7eb73001d3eeb05',
          media: [],
          text: '',
        },
        kind: 'DND_IMAGE',
        targets: [
          {
            position: {
              x: 262,
              y: 350,
            },
            id: '6405c074ff0f5ff3b5f6e026',
          },
          {
            position: {
              x: 537,
              y: 506,
            },
            id: '6405c094ff0f5ff3b5f6e02e',
          },
          {
            position: {
              x: 285,
              y: 498,
            },
            id: '6405c0acff0f5ff3b5f6e030',
          },
          {
            position: {
              x: 300,
              y: 190,
            },
            id: '6405c0d1ff0f5ff3b5f6e032',
          },
          {
            position: {
              x: 88,
              y: 515,
            },
            id: '6405c824ff0f5ff3b5f6e71d',
          },
        ],
        answer: [
          {
            optionId: [
              '6405c015ff0f5ff3b5f6e01a',
            ],
            targetId: '6405c074ff0f5ff3b5f6e026',
          },
          {
            optionId: [
              '6405c08fff0f5ff3b5f6e02d',
            ],
            targetId: '6405c094ff0f5ff3b5f6e02e',
          },
          {
            optionId: [
              '6405c0a4ff0f5ff3b5f6e02f',
            ],
            targetId: '6405c0acff0f5ff3b5f6e030',
          },
          {
            optionId: [
              '6405c0caff0f5ff3b5f6e031',
            ],
            targetId: '6405c0d1ff0f5ff3b5f6e032',
          },
          {
            optionId: [
              '6405c015ff0f5ff3b5f6e01c',
            ],
            targetId: '6405c824ff0f5ff3b5f6e71d',
          },
        ],
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0e1ff0f5ff3b5f6e035',
            text: 'Russia',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0d7ff0f5ff3b5f6e033',
            text: 'Ukraine',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0caff0f5ff3b5f6e031',
            text: 'Sweden',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0a4ff0f5ff3b5f6e02f',
            text: 'Italy',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c08fff0f5ff3b5f6e02d',
            text: 'Turkey',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c088ff0f5ff3b5f6e02b',
            text: 'United Kingdom',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c082ff0f5ff3b5f6e029',
            text: 'Norway',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e019',
            text: 'France',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e01a',
            text: 'Germany',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e01c',
            text: 'Spain',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: -1,
          _id: '6405c0f1549376001d483513',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/bedabe38-2a7c-432a-b460-ac72db28a9f9-v2',
              meta: {
                width: 1946,
                height: 2000,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>Place the countries in their correct locations.</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T10:59:01.387Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 90000,
    },
    {
      _id: '6405c00421e975001d68460e',
      type: 'HOTSPOT',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405c00421e975001d684610',
          media: [],
          text: '',
        },
        answer: [
          '6405bffaff0f5ff3b5f6dffb',
          '6405bff3ff0f5ff3b5f6dff7',
        ],
        kind: 'HOTSPOT',
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            geometry: {
              points: [
                {
                  x: 158,
                  y: 175,
                },
              ],
              shape: 'rectangle',
              height: 32,
              width: 248,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405bfe7ff0f5ff3b5f6dff2',
            text: '',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            geometry: {
              points: [
                {
                  x: 187,
                  y: 249,
                },
              ],
              shape: 'rectangle',
              height: 34,
              width: 272,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405bfedff0f5ff3b5f6dff4',
            text: '',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            geometry: {
              points: [
                {
                  x: 265,
                  y: 326,
                },
              ],
              shape: 'rectangle',
              height: 31,
              width: 269,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405bff3ff0f5ff3b5f6dff7',
            text: '',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            geometry: {
              points: [
                {
                  x: 32.5,
                  y: 491,
                },
              ],
              shape: 'rectangle',
              height: 38,
              width: 323,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405bffaff0f5ff3b5f6dffb',
            text: '',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: -1,
          _id: '6405c00421e975001d68460f',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/a4596767-346c-4102-9aa8-24c8c170896f-v2',
              meta: {
                width: 1024,
                height: 1024,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>Which boxes are around similies?</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T10:27:16.675Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 90000,
    },
    {
      _id: '6405c719ee0b3e001d12b1ae',
      type: 'EQUATION',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405c719ee0b3e001d12b1b2',
          media: [],
          text: '',
        },
        kind: 'EQUATION',
        options: [
          {
            math: {
              latex: [
                '11\\frac{6}{9}',
              ],
              template: null,
            },
            type: 'text',
            hasMath: true,
            answerTime: 0,
            media: [],
            _id: '6405c717ff0f5ff3b5f6e5db',
            text: '<p><katex latex="11\\frac{6}{9}"></katex></p>',
            matcher: 'equivalence',
          },
        ],
        query: {
          math: {
            latex: [
              '6\\frac{5}{9}',
              '5\\frac{1}{9}',
            ],
            template: '<p>A cake recipe called for using {$0}> cups of sugar before baking and another {$1}>cups after baking. What is the total amount of sugar needed in the recipe?</p>',
          },
          type: 'text_image',
          hasMath: true,
          answerTime: -1,
          _id: '6405bcb3c2583b001d6326a2',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/4dacf2cb-d149-4a18-8720-9bd4054e86ff-v2',
              meta: {
                width: 750,
                height: 868,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>A cake recipe called for using <katex latex="6\\frac{5}{9}"></katex> cups of sugar before baking and another <katex latex="5\\frac{1}{9}"></katex>cups after baking. What is the total amount of sugar needed in the recipe?</p>',
        },
        hasMath: false,
        answer: 0,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T10:57:29.484Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 120000,
    },
    {
      _id: '6405b1f6e8a6a7001ddc7e3c',
      type: 'DROPDOWN',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405b22efd1919001da9c0fa',
          media: [],
          text: '',
        },
        kind: 'DROPDOWN',
        answer: [
          {
            optionId: [
              '6405b1dfff0f5ff3b5f6df90',
            ],
            targetId: 'Unais4KOFgom}',
          },
          {
            optionId: [
              '6405b1e3ff0f5ff3b5f6df92',
            ],
            targetId: 'iqHiFx66P3RB}',
          },
        ],
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b1dfff0f5ff3b5f6df90',
            text: 'Helium',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b1e3ff0f5ff3b5f6df92',
            text: 'gravity',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b1e4ff0f5ff3b5f6df93',
            text: 'Hydrogen',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b1e4ff0f5ff3b5f6df93',
            text: 'Oxygen',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b1ebff0f5ff3b5f6df96',
            text: 'fire',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b22aff0f5ff3b5f6dfc0',
            text: 'balloons',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: -1,
          _id: '6405b1f6e8a6a7001ddc7e3d',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/a5d0c4ca-7924-449a-aada-fd02ee27b527-v2',
              meta: {
                width: 1200,
                height: 801,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>​ <blank id="Unais4KOFgom}">Helium</blank>  has the ability to work against ​ <blank id="iqHiFx66P3RB}">gravity</blank> .</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:27:18.551Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 90000,
    },
    {
      _id: '6405b19749f350001defe03e',
      type: 'DRAGNDROP',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: true,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405b236e741ef001d8e67a5',
          media: [],
          text: '',
        },
        kind: 'DRAGNDROP',
        answer: [
          {
            optionId: [
              '6405b0c4ff0f5ff3b5f6df63',
            ],
            targetId: 'NupujKT09m_S}',
          },
          {
            optionId: [
              '6405b145ff0f5ff3b5f6df69',
            ],
            targetId: 'wfbKzfsdd30d}',
          },
          {
            optionId: [
              '6405b116ff0f5ff3b5f6df67',
            ],
            targetId: 'vYCiXfN87Jbz}',
          },
          {
            optionId: [
              '6405b0c4ff0f5ff3b5f6df63',
            ],
            targetId: '4Y788IMKp-I6}',
          },
          {
            optionId: [
              '6405b145ff0f5ff3b5f6df69',
            ],
            targetId: 'VTP_-YvgTQc-}',
          },
        ],
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b0c4ff0f5ff3b5f6df63',
            text: 'the',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b145ff0f5ff3b5f6df69',
            text: 'an',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b116ff0f5ff3b5f6df67',
            text: 'a',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text',
          hasMath: false,
          answerTime: -1,
          _id: '6405b19749f350001defe03f',
          media: [],
          text: "<p>Fill in the correct article (A, AN, or THE)</p><p></p><p></p><p>What's ​ <blank id=\"NupujKT09m_S}\"></blank> capital of your country?</p><p>The car sped past at 100 miles​ <blank id=\"wfbKzfsdd30d}\"></blank> hour</p><p>We noticed ​ <blank id=\"vYCiXfN87Jbz}\"></blank> strong smell coming from ​ <blank id=\"4Y788IMKp-I6}\"></blank> refrigerator.</p><p>He should have called me ​ <blank id=\"VTP_-YvgTQc-}\"></blank> hour ago.</p><p></p>",
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:25:43.838Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 90000,
    },
    {
      _id: '6405b029985afb001d246ef9',
      type: 'REORDER',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [
          0,
          1,
          2,
          3,
          4,
        ],
        order: 'asc',
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405b25e15c4e6001f24b2c2',
          media: [],
          text: '',
        },
        kind: 'REORDER',
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b022ff0f5ff3b5f6df41',
            text: '<p>they</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b024ff0f5ff3b5f6df45',
            text: "<p>can't</p>",
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b025ff0f5ff3b5f6df47',
            text: '<p>dance</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b026ff0f5ff3b5f6df4a',
            text: '<p>very</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405b026ff0f5ff3b5f6df4b',
            text: '<p>well</p>',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: -1,
          _id: '6405b029985afb001d246efa',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/b96fc75c-c29f-4dda-8455-df9ea7ba7b09-v2',
              meta: {
                width: 626,
                height: 348,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>Reorder the following to form a coherent sentence.</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:19:37.987Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 90000,
    },
    {
      _id: '6405b002352827001ed9f7dc',
      type: 'MATCH',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [
          0,
          1,
          2,
          3,
        ],
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405b002352827001ed9f7e6',
          media: [],
          text: '',
        },
        kind: 'MATCH',
        matches: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405afa7ff0f5ff3b5f6df25',
            text: '<p>Abraham Lincoln</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405afb2ff0f5ff3b5f6df27',
            text: '<p>Martin Luther King Jr.</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405af3fff0f5ff3b5f6df1f',
            text: '<p>Florence Nightingale</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405afdfff0f5ff3b5f6df2b',
            text: '<p>Harriet Tubman</p>',
          },
        ],
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'image',
            hasMath: false,
            answerTime: 0,
            media: [
              {
                type: 'image',
                video: '',
                url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/6a66c904-31e5-43a2-94f4-2c968ae7dcd2-v2',
                meta: {
                  width: 400,
                  height: 300,
                  layout: 'contain',
                },
              },
            ],
            _id: '6405afa7ff0f5ff3b5f6df24',
            text: '',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'image',
            hasMath: false,
            answerTime: 0,
            media: [
              {
                type: 'image',
                video: '',
                url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/5d9b3e69-3162-46e4-926b-ebe28b6ee58a-v2',
                meta: {
                  width: 992,
                  height: 1488,
                  layout: 'contain',
                },
              },
            ],
            _id: '6405afb2ff0f5ff3b5f6df26',
            text: '',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'image',
            hasMath: false,
            answerTime: 0,
            media: [
              {
                type: 'image',
                video: '',
                url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/36f92110-5e5e-4214-ae9b-3038a68bc583-v2',
                meta: {
                  width: 1105,
                  height: 1536,
                  layout: 'contain',
                },
              },
            ],
            _id: '6405affbff0f5ff3b5f6df2d',
            text: '',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'image',
            hasMath: false,
            answerTime: 0,
            media: [
              {
                type: 'image',
                video: '',
                url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/7ec6711b-9899-4798-b0a5-ee04adb42410-v2',
                meta: {
                  width: 500,
                  height: 500,
                  layout: 'contain',
                },
              },
            ],
            _id: '6405afebff0f5ff3b5f6df2c',
            text: '',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text',
          hasMath: false,
          answerTime: -1,
          _id: '6405b002352827001ed9f7dd',
          media: [],
          text: '<p>Look at the pictures of historical people below. Match their names to the correct picture.</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:18:58.664Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 90000,
    },
    {
      _id: '6405af385abfd7001d5a9b44',
      type: 'VIDEO',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: false,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [
          -1,
        ],
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405af385abfd7001d5a9b46',
          media: [],
          text: '',
        },
        kind: 'VIDEO',
        options: [],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text',
          hasMath: false,
          answerTime: 30000,
          _id: '6405af385abfd7001d5a9b45',
          media: [],
          text: '<p>Introduce yourself to someone in Spanish.</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:15:36.880Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 600000,
    },
    {
      _id: '6405af1e915ddf001db09fdf',
      type: 'AUDIO',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: false,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [
          -1,
        ],
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405af1e915ddf001db09fe1',
          media: [],
          text: '',
        },
        kind: 'AUDIO',
        options: [],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text',
          hasMath: false,
          answerTime: 10000,
          _id: '6405af1e915ddf001db09fe0',
          media: [],
          text: '<p>How do you pronounce your first name?</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:15:10.979Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 600000,
    },
    {
      _id: '6405af037ddeaf001e3bdc46',
      type: 'DRAW',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: false,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [
          -1,
        ],
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405af037ddeaf001e3bdc48',
          media: [],
          text: '',
        },
        kind: 'DRAW',
        options: [],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text',
          hasMath: false,
          answerTime: -1,
          _id: '6405af037ddeaf001e3bdc47',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/ce001c1c-86c7-4632-9676-0e81b4e269ef-v2',
              meta: {
                width: 880,
                height: 880,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>We have started a drawing for you. Your job is to complete it!</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:14:43.978Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 180000,
    },
    {
      _id: '6405ae0d6a92fc001d97d2fa',
      type: 'MCQ',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: false,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 0,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405ae6cc77a2e001de5638e',
          media: [],
          text: '',
        },
        kind: 'MCQ',
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405ae11ff0f5ff3b5f6df0e',
            text: '<p>have a million dollars in pennies...</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405ae11ff0f5ff3b5f6df0f',
            text: '<p>have a hundred million dollars worth of ice cream...</p>',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: -1,
          _id: '6405ae0d6a92fc001d97d2fd',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/2197d98d-1b10-440c-ad60-593577b65456-v2',
              meta: {
                width: 1300,
                height: 956,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>Would you rather...</p>',
        },
        hasMath: false,
        answer: -1,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:10:37.735Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 30000,
    },
    {
      _id: '6405ad7bca6484001d21adc7',
      type: 'OPEN',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: false,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [
          {
            targetId: '6405c073ff0f5ff3b5f6e025',
            optionId: [
              '6405c015ff0f5ff3b5f6e019',
            ],
          },
          {
            targetId: '6405c074ff0f5ff3b5f6e026',
            optionId: [
              '6405c015ff0f5ff3b5f6e01a',
            ],
          },
          {
            targetId: '6405c075ff0f5ff3b5f6e028',
            optionId: [
              '6405c015ff0f5ff3b5f6e01c',
            ],
          },
          {
            targetId: '6405c085ff0f5ff3b5f6e02a',
            optionId: [
              '6405c082ff0f5ff3b5f6e029',
            ],
          },
          {
            targetId: '6405c08cff0f5ff3b5f6e02c',
            optionId: [
              '6405c088ff0f5ff3b5f6e02b',
            ],
          },
          {
            targetId: '6405c094ff0f5ff3b5f6e02e',
            optionId: [
              '6405c08fff0f5ff3b5f6e02d',
            ],
          },
          {
            targetId: '6405c0acff0f5ff3b5f6e030',
            optionId: [
              '6405c0a4ff0f5ff3b5f6e02f',
            ],
          },
          {
            targetId: '6405c0d1ff0f5ff3b5f6e032',
            optionId: [
              '6405c0caff0f5ff3b5f6e031',
            ],
          },
          {
            targetId: '6405c0dcff0f5ff3b5f6e034',
            optionId: [
              '6405c0d7ff0f5ff3b5f6e033',
            ],
          },
          {
            targetId: '6405c0e4ff0f5ff3b5f6e036',
            optionId: [
              '6405c0e1ff0f5ff3b5f6e035',
            ],
          },
        ],
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405c33c052cdb001d6f227c',
          media: [],
          text: '',
        },
        kind: 'OPEN',
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0e1ff0f5ff3b5f6e035',
            text: 'Russia',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0d7ff0f5ff3b5f6e033',
            text: 'Ukraine',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0caff0f5ff3b5f6e031',
            text: 'Finland',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c0a4ff0f5ff3b5f6e02f',
            text: 'Italy',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c08fff0f5ff3b5f6e02d',
            text: 'Turkey',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c088ff0f5ff3b5f6e02b',
            text: 'United Kingdom',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c082ff0f5ff3b5f6e029',
            text: 'Norway',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e019',
            text: 'France',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e01a',
            text: 'Germany',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405c015ff0f5ff3b5f6e01c',
            text: 'Spain',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_audio',
          hasMath: false,
          answerTime: -1,
          _id: '6405ad7bca6484001d21adc8',
          media: [
            {
              type: 'audio',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/_audio/audioQuestions/7b389b78-cdf8-4a8d-95da-7cb80987789f-v2',
              meta: {
                width: 0,
                height: 0,
                text: '',
                bgColor: '',
                layout: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>Listen to the audio and answer the question.</p><p></p><p>Why does Paul like summer?</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:08:11.032Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 180000,
    },
    {
      _id: '6405ad591db8d5001e1930df',
      type: 'BLANK',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        answer: [],
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: '',
          hasMath: false,
          answerTime: 0,
          _id: '6405ad591db8d5001e1930e2',
          media: [],
          text: '',
        },
        kind: 'BLANK',
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405ab93ff0f5ff3b5f6deda',
            text: '3.14',
            matcher: 'contains',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: -1,
          _id: '6405ad591db8d5001e1930e0',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/d2bd38a2-81e0-4ba7-b615-50e4fed0b703-v2',
              meta: {
                width: 960,
                height: 640,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>What are the first 3 digits of Pi (π)?</p>',
        },
        hasMath: false,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T09:07:37.941Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 60000,
    },
    {
      _id: '6405a94f5abfd7001d587112',
      type: 'MCQ',
      published: true,
      structure: {
        settings: {
          hasCorrectAnswer: true,
          fibDataType: 'string',
          canSubmitCustomResponse: false,
          doesOptionHaveMultipleTargets: false,
        },
        marks: {
          correct: 1,
          incorrect: 0,
        },
        theme: {
          fontColor: {
            text: '#5D2057',
          },
          background: {
            color: '#FFFFFF',
            image: '',
            video: '',
          },
          shape: {
            largeShapeColor: '#F2F2F2',
            smallShapeColor: '#9A4292',
          },
          titleFontFamily: 'Quicksand',
          fontFamily: 'Quicksand',
        },
        explain: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: 0,
          _id: '6405a94f5abfd7001d587116',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/c786eec0-50e5-4f62-9571-c7876003926d-v2',
              meta: {
                width: 400,
                height: 300,
                layout: 'contain',
              },
            },
          ],
          text: '<p>Bananas are a common example of a natural radiation source.</p><p></p><p>They contain high levels of potassium, and a small amount of this is radioactive.</p>',
        },
        kind: 'MCQ',
        options: [
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405a91eff0f5ff3b5f6de6b',
            text: '<p>True</p>',
          },
          {
            math: {
              latex: [],
              template: null,
            },
            type: 'text',
            hasMath: false,
            answerTime: 0,
            media: [],
            _id: '6405a91fff0f5ff3b5f6de6e',
            text: '<p>False</p>',
          },
        ],
        query: {
          math: {
            latex: [],
            template: null,
          },
          type: 'text_image',
          hasMath: false,
          answerTime: -1,
          _id: '6405a94f5abfd7001d587115',
          media: [
            {
              type: 'image',
              video: '',
              url: 'https://media.quizizz.com/_mdserver/main/media/resource/gs/quizizz-media/quizzes/cc5452b7-7ffd-4753-aa96-ee559622c2cc-v2',
              meta: {
                width: 960,
                height: 412,
                layout: 'contain',
                text: '',
                bgColor: '',
                videoId: '',
                start: 0,
                end: 0,
                duration: 0,
                kind: '',
                embeddable: true,
                title: '',
              },
            },
          ],
          text: '<p>Bananas are radioactive</p>',
        },
        hasMath: false,
        answer: 0,
      },
      standards: [],
      topics: [],
      isSuperParent: false,
      createdAt: '2023-03-06T08:50:23.112Z',
      updated: '2023-03-10T10:56:31.387Z',
      standardIds: [],
      cached: true,
      time: 30000,
    },
  ],
};
