export default {
  CT_CLICKED_LOCKED_ADD_A_CO_TEACHER: 'CT_CLICKED_LOCKED_ADD_A_CO_TEACHER',

  CT_CLICKED_UPGRADE_NOW: 'CT_CLICKED_UPGRADE_NOW',

  CT_UPGRADE_UPSELL_BANNER_UPGRADE_TO_SCHOOL_PLAN_CLICKED: 'CT_UPGRADE_UPSELL_BANNER_UPGRADE_TO_SCHOOL_PLAN_CLICKED',
  CT_UPGRADE_UPSELL_BANNER_CANCELED: 'CT_UPGRADE_UPSELL_BANNER_CANCELED',

  CT_INFO_BANNER_CANCELED: 'CT_INFO_BANNER_CANCELED',

  CT_CLICKED_ADD_A_CO_TEACHER: 'CT_CLICKED_ADD_A_CO_TEACHER',
  CT_CO_TEACHER_ADDED: 'CT_CO_TEACHER_ADDED',
  CT_CO_TEACHER_REMOVED: 'CT_CO_TEACHER_REMOVED',
  CT_CO_TEACHER_REMOVAL_POPUP_SHOWN: 'CT_CO_TEACHER_REMOVAL_POPUP_SHOWN',
  CT_CLICKED_VIEW_MEMBERS: 'CT_CLICKED_VIEW_MEMBERS',

  // tooltips
  CT_MENU_TOOLTIP_FULFILLED: 'CT_MENU_TOOLTIP_FULFILLED',
  CT_SIDEBAR_TOOLTIP_HOVERED: 'CT_SIDEBAR_TOOLTIP_HOVERED',

  // error
  CT_ADDED_INVALID_EMAIL: 'CT_ADDED_INVALID_EMAIL',

  CT_REFRESH_CLASS_ROASTER_AS_CO_TEACHER: 'CT_REFRESH_CLASS_ROASTER_AS_CO_TEACHER',

  // game settings
  CT_GAME_SETTINGS_ADD_CO_TEACHER_CLICKED: 'CT_GAME_SETTINGS_ADD_CO_TEACHER_CLICKED',
};
