export default {
  TIMELINE: {
    QBANK: 'gameSettings-qbank',
    QBANK_PINNED: 'gameSettings-qbank_pinned',
    TEST_TIMER_PINNED: 'gamesettings-hardTimer_pinned',
    TIME_CUSTOM_TOGGLED: 'gamesettings_time_custom_toggled',
    NO_DEALINE_TOGGLED: 'gamesettings_nodeadline_toggled',
  },
  MODE_SELECTION: 'gamesettings_mode_selection',
  SKIP_QUESTIONS: 'gamesettings_skip_question',
  REDEMPTION_QUIZ: 'rdq_gamesettings',
  MASTERY_MODE: 'gamesettings_mastery_mode',
  REVIEW_AND_SUBMIT: 'gamesettings_review_and_submit',
  NAME_FACTORY: 'gamesettings_name_factory',
  PARTICIPANT_ATTEMPTS: 'gamesettings_participant_attempts',
  SHOW_ANSWER_DURING_ACTIVITY: 'gamesettings_answers_during_activity',
  SHOW_ANSWER_AFTER_ACTIVITY: 'gamesettings_answers_after_activity',
  REDEMPTION_QUESTION: 'gamesettings_redemption_question',
  EXTRA_LIFE: 'gamesettings_extra_life',
  POWER_UPS: 'gamesettings_powers_ups',
  QUESTION_TIMER: 'gamesettings_questions_timer',
  LIVE_REACTIONS: 'gamesettings_live_reaction',
  SHOW_LEADERBOARD: 'gamesettings_show_leaderboard',
  SHUFFLE_QUESTIONS: 'gamesettings_shuffle_questions',
  SHUFFLE_ANSWER_OPTIONS: 'gamesettings_shuffle_answer_options',
  PLAY_MUSIC: 'gamesettings_play_music',
  SHOW_MEMES: 'gamesettings_show_memes',
  CLASS_SELECTED: 'class_selected',
};
