export default [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    text: 'English',
    val: 'English',
    key: 'langs',
  },
  {
    code: 'es',
    name: 'Spanish; Castilian',
    nativeName: 'español, castellano',
    text: 'Spanish; Castilian',
    val: 'Spanish; Castilian',
    key: 'langs',
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    text: 'Indonesian',
    val: 'Indonesian',
    key: 'langs',
  },
  {
    code: 'ab',
    name: 'Abkhaz',
    nativeName: 'аҧсуа',
    text: 'Abkhaz',
    val: 'Abkhaz',
    key: 'langs',
  },
  {
    code: 'aa',
    name: 'Afar',
    nativeName: 'Afaraf',
    text: 'Afar',
    val: 'Afar',
    key: 'langs',
  },
  {
    code: 'af',
    name: 'Afrikaans',
    nativeName: 'Afrikaans',
    text: 'Afrikaans',
    val: 'Afrikaans',
    key: 'langs',
  },
  {
    code: 'ak',
    name: 'Akan',
    nativeName: 'Akan',
    text: 'Akan',
    val: 'Akan',
    key: 'langs',
  },
  {
    code: 'sq',
    name: 'Albanian',
    nativeName: 'Shqip',
    text: 'Albanian',
    val: 'Albanian',
    key: 'langs',
  },
  {
    code: 'am',
    name: 'Amharic',
    nativeName: 'አማርኛ',
    text: 'Amharic',
    val: 'Amharic',
    key: 'langs',
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    text: 'Arabic',
    val: 'Arabic',
    key: 'langs',
  },
  {
    code: 'an',
    name: 'Aragonese',
    nativeName: 'Aragonés',
    text: 'Aragonese',
    val: 'Aragonese',
    key: 'langs',
  },
  {
    code: 'hy',
    name: 'Armenian',
    nativeName: 'Հայերեն',
    text: 'Armenian',
    val: 'Armenian',
    key: 'langs',
  },
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    text: 'Assamese',
    val: 'Assamese',
    key: 'langs',
  },
  {
    code: 'av',
    name: 'Avaric',
    nativeName: 'авар мацӀ, магӀарул мацӀ',
    text: 'Avaric',
    val: 'Avaric',
    key: 'langs',
  },
  {
    code: 'ae',
    name: 'Avestan',
    nativeName: 'avesta',
    text: 'Avestan',
    val: 'Avestan',
    key: 'langs',
  },
  {
    code: 'ay',
    name: 'Aymara',
    nativeName: 'aymar aru',
    text: 'Aymara',
    val: 'Aymara',
    key: 'langs',
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    nativeName: 'azərbaycan dili',
    text: 'Azerbaijani',
    val: 'Azerbaijani',
    key: 'langs',
  },
  {
    code: 'bm',
    name: 'Bambara',
    nativeName: 'bamanankan',
    text: 'Bambara',
    val: 'Bambara',
    key: 'langs',
  },
  {
    code: 'ba',
    name: 'Bashkir',
    nativeName: 'башҡорт теле',
    text: 'Bashkir',
    val: 'Bashkir',
    key: 'langs',
  },
  {
    code: 'eu',
    name: 'Basque',
    nativeName: 'euskara, euskera',
    text: 'Basque',
    val: 'Basque',
    key: 'langs',
  },
  {
    code: 'be',
    name: 'Belarusian',
    nativeName: 'Беларуская',
    text: 'Belarusian',
    val: 'Belarusian',
    key: 'langs',
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    text: 'Bengali',
    val: 'Bengali',
    key: 'langs',
  },
  {
    code: 'bh',
    name: 'Bihari',
    nativeName: 'भोजपुरी',
    text: 'Bihari',
    val: 'Bihari',
    key: 'langs',
  },
  {
    code: 'bi',
    name: 'Bislama',
    nativeName: 'Bislama',
    text: 'Bislama',
    val: 'Bislama',
    key: 'langs',
  },
  {
    code: 'bs',
    name: 'Bosnian',
    nativeName: 'bosanski jezik',
    text: 'Bosnian',
    val: 'Bosnian',
    key: 'langs',
  },
  {
    code: 'br',
    name: 'Breton',
    nativeName: 'brezhoneg',
    text: 'Breton',
    val: 'Breton',
    key: 'langs',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    nativeName: 'български език',
    text: 'Bulgarian',
    val: 'Bulgarian',
    key: 'langs',
  },
  {
    code: 'my',
    name: 'Burmese',
    nativeName: 'ဗမာစာ',
    text: 'Burmese',
    val: 'Burmese',
    key: 'langs',
  },
  {
    code: 'ca',
    name: 'Catalan; Valencian',
    nativeName: 'Català',
    text: 'Catalan; Valencian',
    val: 'Catalan; Valencian',
    key: 'langs',
  },
  {
    code: 'ch',
    name: 'Chamorro',
    nativeName: 'Chamoru',
    text: 'Chamorro',
    val: 'Chamorro',
    key: 'langs',
  },
  {
    code: 'ce',
    name: 'Chechen',
    nativeName: 'нохчийн мотт',
    text: 'Chechen',
    val: 'Chechen',
    key: 'langs',
  },
  {
    code: 'ny',
    name: 'Chichewa; Chewa; Nyanja',
    nativeName: 'chiCheŵa, chinyanja',
    text: 'Chichewa; Chewa; Nyanja',
    val: 'Chichewa; Chewa; Nyanja',
    key: 'langs',
  },
  {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文 (Zhōngwén), 汉语, 漢語',
    text: 'Chinese',
    val: 'Chinese',
    key: 'langs',
  },
  {
    code: 'cv',
    name: 'Chuvash',
    nativeName: 'чӑваш чӗлхи',
    text: 'Chuvash',
    val: 'Chuvash',
    key: 'langs',
  },
  {
    code: 'kw',
    name: 'Cornish',
    nativeName: 'Kernewek',
    text: 'Cornish',
    val: 'Cornish',
    key: 'langs',
  },
  {
    code: 'co',
    name: 'Corsican',
    nativeName: 'corsu, lingua corsa',
    text: 'Corsican',
    val: 'Corsican',
    key: 'langs',
  },
  {
    code: 'cr',
    name: 'Cree',
    nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ',
    text: 'Cree',
    val: 'Cree',
    key: 'langs',
  },
  {
    code: 'hr',
    name: 'Croatian',
    nativeName: 'hrvatski',
    text: 'Croatian',
    val: 'Croatian',
    key: 'langs',
  },
  {
    code: 'cs',
    name: 'Czech',
    nativeName: 'česky, čeština',
    text: 'Czech',
    val: 'Czech',
    key: 'langs',
  },
  {
    code: 'da',
    name: 'Danish',
    nativeName: 'dansk',
    text: 'Danish',
    val: 'Danish',
    key: 'langs',
  },
  {
    code: 'dv',
    name: 'Divehi; Dhivehi; Maldivian;',
    nativeName: 'ދިވެހި',
    text: 'Divehi; Dhivehi; Maldivian;',
    val: 'Divehi; Dhivehi; Maldivian;',
    key: 'langs',
  },
  {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands, Vlaams',
    text: 'Dutch',
    val: 'Dutch',
    key: 'langs',
  },
  {
    code: 'eo',
    name: 'Esperanto',
    nativeName: 'Esperanto',
    text: 'Esperanto',
    val: 'Esperanto',
    key: 'langs',
  },
  {
    code: 'et',
    name: 'Estonian',
    nativeName: 'eesti, eesti keel',
    text: 'Estonian',
    val: 'Estonian',
    key: 'langs',
  },
  {
    code: 'ee',
    name: 'Ewe',
    nativeName: 'Eʋegbe',
    text: 'Ewe',
    val: 'Ewe',
    key: 'langs',
  },
  {
    code: 'fo',
    name: 'Faroese',
    nativeName: 'føroyskt',
    text: 'Faroese',
    val: 'Faroese',
    key: 'langs',
  },
  {
    code: 'fj',
    name: 'Fijian',
    nativeName: 'vosa Vakaviti',
    text: 'Fijian',
    val: 'Fijian',
    key: 'langs',
  },
  {
    code: 'fi',
    name: 'Finnish',
    nativeName: 'suomi, suomen kieli',
    text: 'Finnish',
    val: 'Finnish',
    key: 'langs',
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'français, langue française',
    text: 'French',
    val: 'French',
    key: 'langs',
  },
  {
    code: 'ff',
    name: 'Fula; Fulah; Pulaar; Pular',
    nativeName: 'Fulfulde, Pulaar, Pular',
    text: 'Fula; Fulah; Pulaar; Pular',
    val: 'Fula; Fulah; Pulaar; Pular',
    key: 'langs',
  },
  {
    code: 'gl',
    name: 'Galician',
    nativeName: 'Galego',
    text: 'Galician',
    val: 'Galician',
    key: 'langs',
  },
  {
    code: 'ka',
    name: 'Georgian',
    nativeName: 'ქართული',
    text: 'Georgian',
    val: 'Georgian',
    key: 'langs',
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    text: 'German',
    val: 'German',
    key: 'langs',
  },
  {
    code: 'el',
    name: 'Greek, Modern',
    nativeName: 'Ελληνικά',
    text: 'Greek, Modern',
    val: 'Greek, Modern',
    key: 'langs',
  },
  {
    code: 'gn',
    name: 'Guaraní',
    nativeName: 'Avañeẽ',
    text: 'Guaraní',
    val: 'Guaraní',
    key: 'langs',
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    text: 'Gujarati',
    val: 'Gujarati',
    key: 'langs',
  },
  {
    code: 'ht',
    name: 'Haitian; Haitian Creole',
    nativeName: 'Kreyòl ayisyen',
    text: 'Haitian; Haitian Creole',
    val: 'Haitian; Haitian Creole',
    key: 'langs',
  },
  {
    code: 'ha',
    name: 'Hausa',
    nativeName: 'Hausa, هَوُسَ',
    text: 'Hausa',
    val: 'Hausa',
    key: 'langs',
  },
  {
    code: 'he',
    name: 'Hebrew (modern)',
    nativeName: 'עברית',
    text: 'Hebrew (modern)',
    val: 'Hebrew (modern)',
    key: 'langs',
  },
  {
    code: 'hz',
    name: 'Herero',
    nativeName: 'Otjiherero',
    text: 'Herero',
    val: 'Herero',
    key: 'langs',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी, हिंदी',
    text: 'Hindi',
    val: 'Hindi',
    key: 'langs',
  },
  {
    code: 'ho',
    name: 'Hiri Motu',
    nativeName: 'Hiri Motu',
    text: 'Hiri Motu',
    val: 'Hiri Motu',
    key: 'langs',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    nativeName: 'Magyar',
    text: 'Hungarian',
    val: 'Hungarian',
    key: 'langs',
  },
  {
    code: 'ia',
    name: 'Interlingua',
    nativeName: 'Interlingua',
    text: 'Interlingua',
    val: 'Interlingua',
    key: 'langs',
  },
  {
    code: 'ie',
    name: 'Interlingue',
    nativeName: 'Originally called Occidental; then Interlingue after WWII',
    text: 'Interlingue',
    val: 'Interlingue',
    key: 'langs',
  },
  {
    code: 'ga',
    name: 'Irish',
    nativeName: 'Gaeilge',
    text: 'Irish',
    val: 'Irish',
    key: 'langs',
  },
  {
    code: 'ig',
    name: 'Igbo',
    nativeName: 'Asụsụ Igbo',
    text: 'Igbo',
    val: 'Igbo',
    key: 'langs',
  },
  {
    code: 'ik',
    name: 'Inupiaq',
    nativeName: 'Iñupiaq, Iñupiatun',
    text: 'Inupiaq',
    val: 'Inupiaq',
    key: 'langs',
  },
  {
    code: 'io',
    name: 'Ido',
    nativeName: 'Ido',
    text: 'Ido',
    val: 'Ido',
    key: 'langs',
  },
  {
    code: 'is',
    name: 'Icelandic',
    nativeName: 'Íslenska',
    text: 'Icelandic',
    val: 'Icelandic',
    key: 'langs',
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    text: 'Italian',
    val: 'Italian',
    key: 'langs',
  },
  {
    code: 'iu',
    name: 'Inuktitut',
    nativeName: 'ᐃᓄᒃᑎᑐᑦ',
    text: 'Inuktitut',
    val: 'Inuktitut',
    key: 'langs',
  },
  {
    code: 'zu',
    name: 'isiZulu',
    nativeName: 'Zulu',
    text: 'isiZulu',
    val: 'isiZulu',
    key: 'langs',
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語 (にほんご／にっぽんご)',
    text: 'Japanese',
    val: 'Japanese',
    key: 'langs',
  },
  {
    code: 'jv',
    name: 'Javanese',
    nativeName: 'basa Jawa',
    text: 'Javanese',
    val: 'Javanese',
    key: 'langs',
  },
  {
    code: 'kl',
    name: 'Kalaallisut, Greenlandic',
    nativeName: 'kalaallisut, kalaallit oqaasii',
    text: 'Kalaallisut, Greenlandic',
    val: 'Kalaallisut, Greenlandic',
    key: 'langs',
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    text: 'Kannada',
    val: 'Kannada',
    key: 'langs',
  },
  {
    code: 'kr',
    name: 'Kanuri',
    nativeName: 'Kanuri',
    text: 'Kanuri',
    val: 'Kanuri',
    key: 'langs',
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'कश्मीरी, كشميري‎',
    text: 'Kashmiri',
    val: 'Kashmiri',
    key: 'langs',
  },
  {
    code: 'kk',
    name: 'Kazakh',
    nativeName: 'Қазақ тілі',
    text: 'Kazakh',
    val: 'Kazakh',
    key: 'langs',
  },
  {
    code: 'km',
    name: 'Khmer',
    nativeName: 'ភាសាខ្មែរ',
    text: 'Khmer',
    val: 'Khmer',
    key: 'langs',
  },
  {
    code: 'ki',
    name: 'Kikuyu, Gikuyu',
    nativeName: 'Gĩkũyũ',
    text: 'Kikuyu, Gikuyu',
    val: 'Kikuyu, Gikuyu',
    key: 'langs',
  },
  {
    code: 'rw',
    name: 'Kinyarwanda',
    nativeName: 'Ikinyarwanda',
    text: 'Kinyarwanda',
    val: 'Kinyarwanda',
    key: 'langs',
  },
  {
    code: 'ky',
    name: 'Kirghiz, Kyrgyz',
    nativeName: 'кыргыз тили',
    text: 'Kirghiz, Kyrgyz',
    val: 'Kirghiz, Kyrgyz',
    key: 'langs',
  },
  {
    code: 'kv',
    name: 'Komi',
    nativeName: 'коми кыв',
    text: 'Komi',
    val: 'Komi',
    key: 'langs',
  },
  {
    code: 'kg',
    name: 'Kongo',
    nativeName: 'KiKongo',
    text: 'Kongo',
    val: 'Kongo',
    key: 'langs',
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어 (韓國語), 조선말 (朝鮮語)',
    text: 'Korean',
    val: 'Korean',
    key: 'langs',
  },
  {
    code: 'ku',
    name: 'Kurdish',
    nativeName: 'Kurdî, كوردی‎',
    text: 'Kurdish',
    val: 'Kurdish',
    key: 'langs',
  },
  {
    code: 'kj',
    name: 'Kwanyama, Kuanyama',
    nativeName: 'Kuanyama',
    text: 'Kwanyama, Kuanyama',
    val: 'Kwanyama, Kuanyama',
    key: 'langs',
  },
  {
    code: 'la',
    name: 'Latin',
    nativeName: 'latine, lingua latina',
    text: 'Latin',
    val: 'Latin',
    key: 'langs',
  },
  {
    code: 'lb',
    name: 'Luxembourgish, Letzeburgesch',
    nativeName: 'Lëtzebuergesch',
    text: 'Luxembourgish, Letzeburgesch',
    val: 'Luxembourgish, Letzeburgesch',
    key: 'langs',
  },
  {
    code: 'lg',
    name: 'Luganda',
    nativeName: 'Luganda',
    text: 'Luganda',
    val: 'Luganda',
    key: 'langs',
  },
  {
    code: 'li',
    name: 'Limburgish, Limburgan, Limburger',
    nativeName: 'Limburgs',
    text: 'Limburgish, Limburgan, Limburger',
    val: 'Limburgish, Limburgan, Limburger',
    key: 'langs',
  },
  {
    code: 'ln',
    name: 'Lingala',
    nativeName: 'Lingála',
    text: 'Lingala',
    val: 'Lingala',
    key: 'langs',
  },
  {
    code: 'lo',
    name: 'Lao',
    nativeName: 'ພາສາລາວ',
    text: 'Lao',
    val: 'Lao',
    key: 'langs',
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    nativeName: 'lietuvių kalba',
    text: 'Lithuanian',
    val: 'Lithuanian',
    key: 'langs',
  },
  {
    code: 'lu',
    name: 'Luba-Katanga',
    nativeName: '',
    text: 'Luba-Katanga',
    val: 'Luba-Katanga',
    key: 'langs',
  },
  {
    code: 'lv',
    name: 'Latvian',
    nativeName: 'latviešu valoda',
    text: 'Latvian',
    val: 'Latvian',
    key: 'langs',
  },
  {
    code: 'gv',
    name: 'Manx',
    nativeName: 'Gaelg, Gailck',
    text: 'Manx',
    val: 'Manx',
    key: 'langs',
  },
  {
    code: 'mk',
    name: 'Macedonian',
    nativeName: 'македонски јазик',
    text: 'Macedonian',
    val: 'Macedonian',
    key: 'langs',
  },
  {
    code: 'mg',
    name: 'Malagasy',
    nativeName: 'Malagasy fiteny',
    text: 'Malagasy',
    val: 'Malagasy',
    key: 'langs',
  },
  {
    code: 'ms',
    name: 'Malay',
    nativeName: 'bahasa Melayu, بهاس ملايو‎',
    text: 'Malay',
    val: 'Malay',
    key: 'langs',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    text: 'Malayalam',
    val: 'Malayalam',
    key: 'langs',
  },
  {
    code: 'mt',
    name: 'Maltese',
    nativeName: 'Malti',
    text: 'Maltese',
    val: 'Maltese',
    key: 'langs',
  },
  {
    code: 'mi',
    name: 'Māori',
    nativeName: 'te reo Māori',
    text: 'Māori',
    val: 'Māori',
    key: 'langs',
  },
  {
    code: 'mr',
    name: 'Marathi (Marāṭhī)',
    nativeName: 'मराठी',
    text: 'Marathi (Marāṭhī)',
    val: 'Marathi (Marāṭhī)',
    key: 'langs',
  },
  {
    code: 'mh',
    name: 'Marshallese',
    nativeName: 'Kajin M̧ajeļ',
    text: 'Marshallese',
    val: 'Marshallese',
    key: 'langs',
  },
  {
    code: 'mn',
    name: 'Mongolian',
    nativeName: 'монгол',
    text: 'Mongolian',
    val: 'Mongolian',
    key: 'langs',
  },
  {
    code: 'na',
    name: 'Nauru',
    nativeName: 'Ekakairũ Naoero',
    text: 'Nauru',
    val: 'Nauru',
    key: 'langs',
  },
  {
    code: 'nv',
    name: 'Navajo, Navaho',
    nativeName: 'Diné bizaad, Dinékʼehǰí',
    text: 'Navajo, Navaho',
    val: 'Navajo, Navaho',
    key: 'langs',
  },
  {
    code: 'nb',
    name: 'Norwegian Bokmål',
    nativeName: 'Norsk bokmål',
    text: 'Norwegian Bokmål',
    val: 'Norwegian Bokmål',
    key: 'langs',
  },
  {
    code: 'nd',
    name: 'North Ndebele',
    nativeName: 'isiNdebele',
    text: 'North Ndebele',
    val: 'North Ndebele',
    key: 'langs',
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    text: 'Nepali',
    val: 'Nepali',
    key: 'langs',
  },
  {
    code: 'ng',
    name: 'Ndonga',
    nativeName: 'Owambo',
    text: 'Ndonga',
    val: 'Ndonga',
    key: 'langs',
  },
  {
    code: 'nn',
    name: 'Norwegian Nynorsk',
    nativeName: 'Norsk nynorsk',
    text: 'Norwegian Nynorsk',
    val: 'Norwegian Nynorsk',
    key: 'langs',
  },
  {
    code: 'no',
    name: 'Norwegian',
    nativeName: 'Norsk',
    text: 'Norwegian',
    val: 'Norwegian',
    key: 'langs',
  },
  {
    code: 'ii',
    name: 'Nuosu',
    nativeName: 'ꆈꌠ꒿ Nuosuhxop',
    text: 'Nuosu',
    val: 'Nuosu',
    key: 'langs',
  },
  {
    code: 'nr',
    name: 'South Ndebele',
    nativeName: 'isiNdebele',
    text: 'South Ndebele',
    val: 'South Ndebele',
    key: 'langs',
  },
  {
    code: 'oc',
    name: 'Occitan',
    nativeName: 'Occitan',
    text: 'Occitan',
    val: 'Occitan',
    key: 'langs',
  },
  {
    code: 'oj',
    name: 'Ojibwe, Ojibwa',
    nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
    text: 'Ojibwe, Ojibwa',
    val: 'Ojibwe, Ojibwa',
    key: 'langs',
  },
  {
    code: 'cu',
    name: 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
    nativeName: 'ѩзыкъ словѣньскъ',
    text: 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
    val: 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
    key: 'langs',
  },
  {
    code: 'om',
    name: 'Oromo',
    nativeName: 'Afaan Oromoo',
    text: 'Oromo',
    val: 'Oromo',
    key: 'langs',
  },
  {
    code: 'or',
    name: 'Oriya',
    nativeName: 'ଓଡ଼ିଆ',
    text: 'Oriya',
    val: 'Oriya',
    key: 'langs',
  },
  {
    code: 'os',
    name: 'Ossetian, Ossetic',
    nativeName: 'ирон æвзаг',
    text: 'Ossetian, Ossetic',
    val: 'Ossetian, Ossetic',
    key: 'langs',
  },
  {
    code: 'pa',
    name: 'Panjabi, Punjabi',
    nativeName: 'ਪੰਜਾਬੀ, پنجابی‎',
    text: 'Panjabi, Punjabi',
    val: 'Panjabi, Punjabi',
    key: 'langs',
  },
  {
    code: 'pi',
    name: 'Pāli',
    nativeName: 'पाऴि',
    text: 'Pāli',
    val: 'Pāli',
    key: 'langs',
  },
  {
    code: 'fa',
    name: 'Persian',
    nativeName: 'فارسی',
    text: 'Persian',
    val: 'Persian',
    key: 'langs',
  },
  {
    code: 'pl',
    name: 'Polish',
    nativeName: 'polski',
    text: 'Polish',
    val: 'Polish',
    key: 'langs',
  },
  {
    code: 'ps',
    name: 'Pashto, Pushto',
    nativeName: 'پښتو',
    text: 'Pashto, Pushto',
    val: 'Pashto, Pushto',
    key: 'langs',
  },
  {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    text: 'Portuguese',
    val: 'Portuguese',
    key: 'langs',
  },
  {
    code: 'qu',
    name: 'Quechua',
    nativeName: 'Runa Simi, Kichwa',
    text: 'Quechua',
    val: 'Quechua',
    key: 'langs',
  },
  {
    code: 'rm',
    name: 'Romansh',
    nativeName: 'rumantsch grischun',
    text: 'Romansh',
    val: 'Romansh',
    key: 'langs',
  },
  {
    code: 'rn',
    name: 'Kirundi',
    nativeName: 'kiRundi',
    text: 'Kirundi',
    val: 'Kirundi',
    key: 'langs',
  },
  {
    code: 'ro',
    name: 'Romanian, Moldavian, Moldovan',
    nativeName: 'română',
    text: 'Romanian, Moldavian, Moldovan',
    val: 'Romanian, Moldavian, Moldovan',
    key: 'langs',
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'русский язык',
    text: 'Russian',
    val: 'Russian',
    key: 'langs',
  },
  {
    code: 'sa',
    name: 'Sanskrit (Saṁskṛta)',
    nativeName: 'संस्कृतम्',
    text: 'Sanskrit (Saṁskṛta)',
    val: 'Sanskrit (Saṁskṛta)',
    key: 'langs',
  },
  {
    code: 'sc',
    name: 'Sardinian',
    nativeName: 'sardu',
    text: 'Sardinian',
    val: 'Sardinian',
    key: 'langs',
  },
  {
    code: 'sd',
    name: 'Sindhi',
    nativeName: 'सिन्धी, سنڌي، سندھی‎',
    text: 'Sindhi',
    val: 'Sindhi',
    key: 'langs',
  },
  {
    code: 'se',
    name: 'Northern Sami',
    nativeName: 'Davvisámegiella',
    text: 'Northern Sami',
    val: 'Northern Sami',
    key: 'langs',
  },
  {
    code: 'sm',
    name: 'Samoan',
    nativeName: 'gagana faa Samoa',
    text: 'Samoan',
    val: 'Samoan',
    key: 'langs',
  },
  {
    code: 'sg',
    name: 'Sango',
    nativeName: 'yângâ tî sängö',
    text: 'Sango',
    val: 'Sango',
    key: 'langs',
  },
  {
    code: 'sr',
    name: 'Serbian',
    nativeName: 'српски језик',
    text: 'Serbian',
    val: 'Serbian',
    key: 'langs',
  },
  {
    code: 'gd',
    name: 'Scottish Gaelic; Gaelic',
    nativeName: 'Gàidhlig',
    text: 'Scottish Gaelic; Gaelic',
    val: 'Scottish Gaelic; Gaelic',
    key: 'langs',
  },
  {
    code: 'sn',
    name: 'Shona',
    nativeName: 'chiShona',
    text: 'Shona',
    val: 'Shona',
    key: 'langs',
  },
  {
    code: 'si',
    name: 'Sinhala, Sinhalese',
    nativeName: 'සිංහල',
    text: 'Sinhala, Sinhalese',
    val: 'Sinhala, Sinhalese',
    key: 'langs',
  },
  {
    code: 'sk',
    name: 'Slovak',
    nativeName: 'slovenčina',
    text: 'Slovak',
    val: 'Slovak',
    key: 'langs',
  },
  {
    code: 'sl',
    name: 'Slovene',
    nativeName: 'slovenščina',
    text: 'Slovene',
    val: 'Slovene',
    key: 'langs',
  },
  {
    code: 'so',
    name: 'Somali',
    nativeName: 'Soomaaliga, af Soomaali',
    text: 'Somali',
    val: 'Somali',
    key: 'langs',
  },
  {
    code: 'st',
    name: 'Southern Sotho',
    nativeName: 'Sesotho',
    text: 'Southern Sotho',
    val: 'Southern Sotho',
    key: 'langs',
  },
  {
    code: 'su',
    name: 'Sundanese',
    nativeName: 'Basa Sunda',
    text: 'Sundanese',
    val: 'Sundanese',
    key: 'langs',
  },
  {
    code: 'sw',
    name: 'Swahili',
    nativeName: 'Kiswahili',
    text: 'Swahili',
    val: 'Swahili',
    key: 'langs',
  },
  {
    code: 'ss',
    name: 'Swati',
    nativeName: 'SiSwati',
    text: 'Swati',
    val: 'Swati',
    key: 'langs',
  },
  {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'svenska',
    text: 'Swedish',
    val: 'Swedish',
    key: 'langs',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    text: 'Tamil',
    val: 'Tamil',
    key: 'langs',
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    text: 'Telugu',
    val: 'Telugu',
    key: 'langs',
  },
  {
    code: 'tg',
    name: 'Tajik',
    nativeName: 'тоҷикӣ, toğikī, تاجیکی‎',
    text: 'Tajik',
    val: 'Tajik',
    key: 'langs',
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    text: 'Thai',
    val: 'Thai',
    key: 'langs',
  },
  {
    code: 'ti',
    name: 'Tigrinya',
    nativeName: 'ትግርኛ',
    text: 'Tigrinya',
    val: 'Tigrinya',
    key: 'langs',
  },
  {
    code: 'bo',
    name: 'Tibetan Standard, Tibetan, Central',
    nativeName: 'བོད་ཡིག',
    text: 'Tibetan Standard, Tibetan, Central',
    val: 'Tibetan Standard, Tibetan, Central',
    key: 'langs',
  },
  {
    code: 'tk',
    name: 'Turkmen',
    nativeName: 'Türkmen, Түркмен',
    text: 'Turkmen',
    val: 'Turkmen',
    key: 'langs',
  },
  {
    code: 'tl',
    name: 'Tagalog',
    nativeName: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
    text: 'Tagalog',
    val: 'Tagalog',
    key: 'langs',
  },
  {
    code: 'tn',
    name: 'Tswana',
    nativeName: 'Setswana',
    text: 'Tswana',
    val: 'Tswana',
    key: 'langs',
  },
  {
    code: 'to',
    name: 'Tonga (Tonga Islands)',
    nativeName: 'faka Tonga',
    text: 'Tonga (Tonga Islands)',
    val: 'Tonga (Tonga Islands)',
    key: 'langs',
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    text: 'Turkish',
    val: 'Turkish',
    key: 'langs',
  },
  {
    code: 'ts',
    name: 'Tsonga',
    nativeName: 'Xitsonga',
    text: 'Tsonga',
    val: 'Tsonga',
    key: 'langs',
  },
  {
    code: 'tt',
    name: 'Tatar',
    nativeName: 'татарча, tatarça, تاتارچا‎',
    text: 'Tatar',
    val: 'Tatar',
    key: 'langs',
  },
  {
    code: 'tw',
    name: 'Twi',
    nativeName: 'Twi',
    text: 'Twi',
    val: 'Twi',
    key: 'langs',
  },
  {
    code: 'ty',
    name: 'Tahitian',
    nativeName: 'Reo Tahiti',
    text: 'Tahitian',
    val: 'Tahitian',
    key: 'langs',
  },
  {
    code: 'ug',
    name: 'Uighur, Uyghur',
    nativeName: 'Uyƣurqə, ئۇيغۇرچە‎',
    text: 'Uighur, Uyghur',
    val: 'Uighur, Uyghur',
    key: 'langs',
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'українська',
    text: 'Ukrainian',
    val: 'Ukrainian',
    key: 'langs',
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    text: 'Urdu',
    val: 'Urdu',
    key: 'langs',
  },
  {
    code: 'uz',
    name: 'Uzbek',
    nativeName: 'zbek, Ўзбек, أۇزبېك‎',
    text: 'Uzbek',
    val: 'Uzbek',
    key: 'langs',
  },
  {
    code: 've',
    name: 'Venda',
    nativeName: 'Tshivenḓa',
    text: 'Venda',
    val: 'Venda',
    key: 'langs',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    text: 'Vietnamese',
    val: 'Vietnamese',
    key: 'langs',
  },
  {
    code: 'vo',
    name: 'Volapük',
    nativeName: 'Volapük',
    text: 'Volapük',
    val: 'Volapük',
    key: 'langs',
  },
  {
    code: 'wa',
    name: 'Walloon',
    nativeName: 'Walon',
    text: 'Walloon',
    val: 'Walloon',
    key: 'langs',
  },
  {
    code: 'cy',
    name: 'Welsh',
    nativeName: 'Cymraeg',
    text: 'Welsh',
    val: 'Welsh',
    key: 'langs',
  },
  {
    code: 'wo',
    name: 'Wolof',
    nativeName: 'Wollof',
    text: 'Wolof',
    val: 'Wolof',
    key: 'langs',
  },
  {
    code: 'fy',
    name: 'Western Frisian',
    nativeName: 'Frysk',
    text: 'Western Frisian',
    val: 'Western Frisian',
    key: 'langs',
  },
  {
    code: 'xh',
    name: 'Xhosa',
    nativeName: 'isiXhosa',
    text: 'Xhosa',
    val: 'Xhosa',
    key: 'langs',
  },
  {
    code: 'yi',
    name: 'Yiddish',
    nativeName: 'ייִדיש',
    text: 'Yiddish',
    val: 'Yiddish',
    key: 'langs',
  },
  {
    code: 'yo',
    name: 'Yoruba',
    nativeName: 'Yorùbá',
    text: 'Yoruba',
    val: 'Yoruba',
    key: 'langs',
  },
  {
    code: 'za',
    name: 'Zhuang, Chuang',
    nativeName: 'Saɯ cueŋƅ, Saw cuengh',
    text: 'Zhuang, Chuang',
    val: 'Zhuang, Chuang',
    key: 'langs',
  },
];
